name: Deploy Kafka Topology
env:
   BOOTSTRAP_SERVERS: pkc-41mxj.uksouth.azure.confluent.cloud:9092
   CLUSTER_API_KEY: ${{secrets.CLUSTER_API_KEY}}
   CLUSTER_API_SECRET: ${{secrets.CLUSTER_API_SECRET}}
   SR_API_KEY: ${{secrets.SR_API_KEY}}
   SR_API_SECRET: ${{secrets.SR_API_SECRET}}

on: [workflow_dispatch]

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
#on:
#  push:
#    branches: [ master ]
 # pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build Config into image (use volume mount in real pipeline)
        run: |
          ls
          chmod +x ./build-connection-file.sh
          ./build-connection-file.sh > topology-builder.properties
          docker build . -t crazy_fool:latest
      - name: Deploy Topology
        run: |
          docker run crazy_fool:latest kafka-topology-builder.sh  --clientConfig topology-builder.properties --brokers $BOOTSTRAP_SERVERS --topology topology.yaml
